### ISSUE TITLE
百度贴吧被永久封禁，申诉失败， 无限申诉方法

### ISSUE THREAD

**Issue by dxhuii** [dxhuii/blog#5]
电脑版，右键申诉编码，审查元素，然后找到“3”改为“0”回车再点审查元素，就可以再次申请了

**Comment by dupenghuiii** [comment]
现在好像不管用了

**Comment by dxhuii** [comment]
@dupenghuiii 是的，这个是好多年前的，现在也不知道有没有新方法了，不玩贴吧了，也没有研究了。
